### ISSUE TITLE
Problema no primeiro algoritmo da aula Análise Assintótica de Algoritmos

### ISSUE THREAD

**Issue by xarmison** [eduardolfalcao/edii#1]
Problema no primeiro algoritmo mostrado na aula [Análise Assintótica de Algoritmos](https://github.com/eduardolfalcao/edii/blob/master/conteudos/AnaliseAssintotica.md).

O algoritmo falha para a entrada 2.
```c++
//Daniel
bool ehPrimo(unsigned int n){
    for(int i = 2; i < n; i++){
        if(n%i==0){
            return false;
        }
    }
    return true;
}
```

Possível solução para manter a complexidade em O(n):

```c++
bool isPrime(unsigned int n) {
    int divs = 0;
    for(int i = 1; i <= n; i++) {
        if(n%i == 0) {
            divs++;
        }
    }

    if(divs == 2) 
        return true;
    else 
        return false;
}
```

**Comment by xarmison** [comment]
Analisando mais, a função apresentada não entra no for para a entrada igual a dois fazendo o retorno estar correto

**Comment by eduardolfalcao** [comment]
Exatamente. 
De todo modo, obrigado :)
