### ISSUE TITLE
Algumas observações

### ISSUE THREAD

**Issue by xarmison** [eduardolfalcao/edii#3]
- Na [segunda linha](https://github.com/eduardolfalcao/edii/blob/12fb233b53b24305d05560bec15b86152a97812b/tests/testTabelaHash.cpp#L2) está sendo inclusa a biblioteca unordered_map que não é utilizada nos testes sendo assim pode ser removida. Similarmente a [linha 4](https://github.com/eduardolfalcao/edii/blob/12fb233b53b24305d05560bec15b86152a97812b/tests/testTabelaHash.cpp#L4) inclui a bilioteca chrono que também não é utilizada.

- Adicionar a biblioteca algorithm para o uso da função [std::count](https://www.cplusplus.com/reference/algorithm/count/).

- Creio haver faltado comparações nas linhas [43](https://github.com/eduardolfalcao/edii/blob/12fb233b53b24305d05560bec15b86152a97812b/tests/testTabelaHash.cpp#L43) e [57](https://github.com/eduardolfalcao/edii/blob/12fb233b53b24305d05560bec15b86152a97812b/tests/testTabelaHash.cpp#L57), ambas deveriam ser:

```cpp
EXPECT_TRUE(estoqueSupermercadoTabelaHash.contemChave(itens[i] + to_string(j)));
```

**Comment by eduardolfalcao** [comment]
Obrigado @xarmison 

Suas sugestões foram incorporadas [neste commit](https://github.com/eduardolfalcao/edii/commit/de30205794e9fce2bf6daff1aa4bd81daf27ff09) e [neste commit](https://github.com/eduardolfalcao/edii/commit/99737a0285c81a77e3c27c18b1c7ea421d6fb7b4).
