### ISSUE TITLE
Teste referente ao método "haCaminho"

### ISSUE THREAD

**Issue by Enricoufrn** [eduardolfalcao/edii#4]
O grafo construído é um grafo onde todas as arestas são não direcionais, sendo assim, caso o nó v1 seja o parâmetro passado ao método em questão, o resultado deve ser true, indicando que há um caminho saindo de v1 e chegando a v1, diferente do resultado esperado no teste que espera que retorne false. Esse comportamento faz sentido pois as arestas são não direcionais, então uma aresta de v1 a v1 não faria diferença no resultado, entretanto caso as arestas sejam direcionais a implementação do método deve garantir que só será retornado true se de fato houver um caminho ligando v1 a v1.
![image](https://user-images.githubusercontent.com/62080317/149794978-2e6d7b6c-ab41-46a5-bdac-a7dcfc841250.png)

**Comment by eduardolfalcao** [comment]
Obrigado, @Enricoufrn 
A fix da issue demorou mas  @chegou rsrs
