### ISSUE TITLE
Teste referente ao algoritmo de Bellman-Ford

### ISSUE THREAD

**Issue by Enricoufrn** [eduardolfalcao/edii#5]
Na função de teste BellmanFordGrafoCom2ComponentesECicloNegativo quando chamado o método de Bellman-Ford para v10 é esperado que nas posições do array de distâncias que correspondem aos nós, que fazem parte do componente do grafo onde há um ciclo negativo, seja igual a constante NEG_INF, porém esse comportamento depende da implementação, o mais intuitivo é esperar que essas distancias sejam iguais a POS_INF, pois esses nós não estão ligados ao nó usado como exemplo, v10. Esse comportamento é possível caso seja adicionada uma condição a mais ao processo de relaxamento das distâncias. 
Exemplo:
if (distancias[iOrigem] != POS_INF && distancias[iOrigem] + pesoAresta < distancias[iDestino]) {
     distancias[iDestino] = distancias[iOrigem] + pesoAresta;
}
Caso a condição no if não tenha a condicional 'distancias[iOrigem] != POS_INF' o comportamento da implementação será igual ao esperado no teste, entretanto as posições do array de distâncias referentes aos nós que não estão ligados de nenhuma forma a v10 não serão iguais a constante que representa distância máxima.

**Comment by eduardolfalcao** [comment]
Boa, garoto.

Vou incorporar sua sugestão na tarefa desse semestre! Valeu :)
